channels:
 - pyviz
packages:
 - jupyter-panel-proxy
dependencies:
  - python=3.9
  - bokeh=2.4.2
  - param=1.12.0
  - panel=0.14.2
  - nbserverproxy
  - pyviz::param=1.9.0
  - pyviz::pyviz_comms=0.7.2
  - pyviz::datashader
  - bokeh::bokeh
  - tornado>=4.3
  - aiohttp==3.8.1
  - aiosignal==1.2.0
  - async-timeout==4.0.2
  - attrs==21.4.0
  - base58==2.1.1
  - bitarray==1.2.2
  - cached-property==1.5.2
  - certifi==2021.10.8
  - charset-normalizer==2.0.10
  - click==8.0.3
  - colorama==0.4.4
  - commonmark==0.9.1
  - cytoolz==0.11.2
  - distlib==0.3.4
  - eth-abi==2.1.1
  - eth-hash==0.3.2
  - eth-keyfile==0.5.1
  - filelock==3.4.0
  - frozenlist==1.2.0
  - hexbytes==0.2.2
  - idna==3.3
  - ipfshttpclient==0.8.0a2
  - jsonschema==3.2.0
  - lru-dict==1.1.7
  - multiaddr==0.0.9
  - multidict==5.2.0
  - numpy==1.22.3
  - pandas==1.4.2
  - parsimonious==0.8.1
  - pipenv==2021.11.23
  - platformdirs==2.4.0
  - protobuf==3.19.4
  - Pygments==2.11.2
  - pyrsistent==0.18.1
  - python-dateutil==2.8.2
  - python-dotenv==0.19.2
  - pytz==2022.1
  - requests==2.27.1
  - rich==9.13.0
  - rlp==2.0.1
  - six==1.16.0
  - tomlkit==0.10.1
  - toolz==0.11.2
  - typing-extensions==3.10.0.2
  - urllib3==1.26.8
  - varint==1.0.2
  - virtualenv-clone==0.5.7
  - websockets==9.1
  - yarl==1.7.2
